stages:
  - dependencies
  - build
  - docker
  - deploy

node_modules:
  stage: dependencies
  image: node:lts-alpine
  only:
    changes:
      - "backend/yarn.lock"
      - "frontend/yarn.lock"
  tags:
    - docker
  script:
    - cd backend
    - yarn install --cache-folder .yarn --frozen-lockfile
    - cd ../frontend
    - yarn install --cache-folder .yarn --frozen-lockfile
  cache:
    paths:
      - backend/node_modules/
      - backend/.yarn
      - frontend/node_modules/
      - frontend/.yarn
  artifacts:
    untracked: true

build:
  stage: build
  image: node:lts-alpine
  tags:
    - docker
  dependencies:
    - node_modules
  script:
    - cd frontend
    - yarn test
    - yarn build
    - cd ../backend
    - yarn build
    - yarn test
  cache:
    paths:
      - backend/node_modules/
      - backend/.yarn
      - frontend/node_modules/
      - frontend/.yarn
  artifacts:
    untracked: false
    expire_in: 1 days
    paths:
      - "backend/dist"
      - "backend/node_modules"
      - "backend/migrations"
      - "frontend/build"
      - "Dockerfile"

docker-master:
  stage: docker
  tags:
    - stage
  only:
    - master
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.corteks.net
    - docker build -t registry.corteks.net/epitech/chinese-checkers:latest .
    - docker push registry.corteks.net/epitech/chinese-checkers:latest

deploy-net:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - master
  tags:
    - stage
  dependencies:
    - docker-master
  script:
    - >
      docker run --rm -d
      --name mongo.game.corteks.net
      -e MONGODB_DATABASE=chinese-checkers
      -l com.docker.compose.project=game.corteks.net
      mongo
    - docker network connect game_default mongo.game.corteks.net
    - >
      docker run --rm -d
      --name game.corteks.net
      --network corteks_net_nginx_proxy
      -l com.docker.compose.project=game.corteks.net
      -e MONGODB_HOST=mongo.game.corteks.net
      -e VIRTUAL_HOST=game.corteks.net
      -e VIRTUAL_PORT=8080
      -e LETSENCRYPT_HOST=game.corteks.net
      registry.corteks.net/epitech/chinese-checkers:latest
    - docker network connect game_default game.corteks.net
